In [1]:
import numpy as np

In [2]:
# for slicing 3x3 matrix
# slide no,row,column
# i,j,k

In [ ]:
# UIT repository from enggqasim github has all chapters
# random is a package in numpy and has further functions
# np.random.randn(2, 3)
# distributed according to any distribution e.g normal according to bell curve or uniform distribution
# related to stats can also be studied from any course
# Chapter 4 from Book Python for Data Analysis

In [6]:
a = np.arange(1, 28).reshape((3, 3, 3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
# Datatype of all elements of array in numpy is same

In [7]:
a.shape = (3, 9) # will also reshape data and is in-memory(in place) operation

In [8]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [9]:
np.zeros((3, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# copy shape of a and all elements are 0
np.zeros_like(a) # copy of a 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [13]:
np.ones((3, 3, 3, 3))

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [20]:
np.ones((3,3), dtype='int64') # to change datatype from float to int

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [21]:
np.ones((3,3), dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [14]:
np.ones_like(a)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [17]:
np.empty((2, 3, 1)) #sometimes garbage sometimes returns 0

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [16]:
np.empty_like(a)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
np.full((2, 3, 3), fill_value=5) # to get array of any other value

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

In [19]:
np.ones((2, 3)) * 7

array([[7., 7., 7.],
       [7., 7., 7.]])

In [ ]:
np.arange()

In [ ]:
# array > deep copy
# asarray > shallow copy

In [ ]:
# matrix is 2dim array is ndim

In [22]:
# eye, identity function
np.eye(4) #create 4x4 and diagnol is 1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# from numpy import sum
# only sum function is copied from numpy, memory efficient
# optimization in code by this, done in aiot

## DataTypes for ndarrays

In [27]:
a = np.arange(1, 13).astype(np.float64).reshape((3,4))
# chain of commands
# same as reshape(astype(range(1,3)))
# astype is function dtype is attribute
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [40]:
a = np.arange(1, 13).astype(np.character).reshape((3,4))
a

array([[b'1', b'2', b'3', b'4'],
       [b'5', b'6', b'7', b'8'],
       [b'9', b'10', b'11', b'12']], dtype='|S11')

In [38]:
a = np.arange(1, 13).reshape((3,4)).astype(np.float64)
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [39]:
a = np.arange(1, 13, dtype='float').reshape((3, 4))
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [44]:
a = np.array([2, 3, 4], dtype=np.float64 )
a

array([2., 3., 4.])

In [45]:
a1 = np.array([2, 3, 4], dtype=np.int64 )
a1

array([2, 3, 4], dtype=int64)

In [46]:
print(a.dtype)
print(a1.dtype)

float64
int64


In [49]:
print(type(a[0]))
print(type(a1[0]))

<class 'numpy.float64'>
<class 'numpy.int64'>


In [51]:
# unit is unsigned integer
a2 = np.array([1, 3, 6], dtype='int')
a2.dtype

dtype('int32')

In [53]:
a2 = np.array([1, 3, 6], dtype=np.int32)
a2.dtype

dtype('int32')

In [55]:
a2 = np.array([1, 3, 6], dtype='i4')
a2.dtype
# i1, i4, i8 for integer 8, 32 or 64 bits
# i or u

dtype('int32')

In [56]:
a2 = np.array([1, 3, 6], dtype='f4')
print(a2)
# f2, f4, f8
# f or d
a2.dtype

[1. 3. 6.]


dtype('float32')

In [59]:
def abc(x):
    try:
        x = str(x)
        return np.int64("".join([i for i in x if str.isnumeric(i)]))
    except:
        return 0
abc("sdkjsdhjshdjashk:jkjk")

0

In [ ]:
# shift + l to get line numbers

In [ ]:
# complex numbers 
# c8, c16, c32 for complex 32, 64, 128

In [ ]:
# np.set_printoptions(threshold=sys.maxsize)

In [ ]:
# astype dtype
# reshape shape

In [65]:
a = np.array([2, 3, 4], dtype=np.float64 )
b = np.array([2, 3, 4], dtype=np.int64 )
print(a.dtype)
print(b.dtype)

float64
int64


In [66]:
b.astype(a.dtype)

array([2., 3., 4.])

In [91]:
a = np.arange(1, 28).reshape((3, 3, 3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [68]:
a % 5 == 0

array([[[False, False, False],
        [False,  True, False],
        [False, False, False]],

       [[ True, False, False],
        [False, False,  True],
        [False, False, False]],

       [[False,  True, False],
        [False, False, False],
        [ True, False, False]]])

In [69]:
a[a % 5 == 0]

array([ 5, 10, 15, 20, 25])

In [94]:
a[(a%5==0 and a%3==0)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [78]:
a[1][1][1]

14

In [80]:
a[1:,1:,:1]

array([[[13],
        [16]],

       [[22],
        [25]]])

In [83]:
a[1:][1:][1:]

array([], shape=(0, 3, 3), dtype=int32)

In [85]:
a[1,1,1]

14