In [4]:
import numpy as np

In [2]:
a = np.random.randint(1, 20, size=20)
b = np.random.randint(1, 10, size=10)
print(a, b, sep='\n\n')

[11 12  8 14  9  9 11 13  5 16 18  7  6  9 12 10 10 11  7  7]

[2 1 6 9 3 8 1 2 9 7]


In [7]:
# using python
[True if x in a else False for x in b]

[False, False, True, True, False, True, False, False, True, True]

In [9]:
# using numpy
np.in1d(b, a)

array([False, False,  True,  True, False,  True, False, False,  True,
        True])

### Stacking

In [12]:
a = np.arange(1, 11)
b = a * 3
print(a, b, sep='\n\n')
np.stack((a, b), axis=0)

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [13]:
np.stack((a, b), axis=1)

array([[ 1,  3],
       [ 2,  6],
       [ 3,  9],
       [ 4, 12],
       [ 5, 15],
       [ 6, 18],
       [ 7, 21],
       [ 8, 24],
       [ 9, 27],
       [10, 30]])

In [14]:
np.hstack((a,b)) #horizontal stack

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  3,  6,  9, 12, 15, 18, 21,
       24, 27, 30])

In [16]:
np.vstack((a,b)) # vertical stack

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [20]:
a = np.arange(2*2*2).reshape((2,2,2))
b = a + 10
print(a, b , sep='\n\n')

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[[10 11]
  [12 13]]

 [[14 15]
  [16 17]]]


In [21]:
# deep stack
np.dstack((a, b))

array([[[ 0,  1, 10, 11],
        [ 2,  3, 12, 13]],

       [[ 4,  5, 14, 15],
        [ 6,  7, 16, 17]]])

In [23]:
a = np.arange(2*2).reshape((2,2))
print(a, a + 5 , sep='\n\n')

[[0 1]
 [2 3]]

[[5 6]
 [7 8]]


In [24]:
b = np.full_like(a, 5)
print(a, b, sep='\n\n')

[[0 1]
 [2 3]]

[[5 5]
 [5 5]]


In [25]:
a + b

array([[5, 6],
       [7, 8]])

In [27]:
a = np.arange(1, 11)
b = a * 3
print(a, b, sep='\n\n')
np.column_stack((a, b))

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([[ 1,  3],
       [ 2,  6],
       [ 3,  9],
       [ 4, 12],
       [ 5, 15],
       [ 6, 18],
       [ 7, 21],
       [ 8, 24],
       [ 9, 27],
       [10, 30]])

In [28]:
a = np.arange(1, 11)
b = a * 3
print(a, b, sep='\n\n')
np.row_stack((a, b))

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [29]:
a = np.random.randn(6, 5)
a

array([[-1.62861703,  0.92599884, -0.30005273,  0.99727237,  0.568481  ],
       [-0.13755866,  3.56172173, -0.69160052, -0.24058774, -1.05849078],
       [ 0.40168015,  1.17261326,  1.76446881,  0.46108602,  0.50608611],
       [ 2.66431378,  0.10057406, -0.05320486,  0.72694149, -1.12178383],
       [ 0.53641361, -0.51551263,  0.77708884, -1.4056657 ,  0.04604462],
       [-0.22891448,  0.36843045, -2.0899814 , -0.32965925,  2.23610605]])

In [36]:
a = np.arange(6*6).reshape((6,6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [40]:
np.split(a, 2) # row split

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [41]:
np.split(a, 2, axis=1) # column split

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]])]

In [49]:
a = np.random.randint(1, 20, size=20)
b = np.random.randint(1, 10, size=10)
print(a, b, sep='\n\n')
np.intersect1d(a, b)

[10 16  2 18  3  6 11 17 12  3 18 16 18 10 14 18  4  1  9  9]

[4 5 1 1 1 7 8 7 3 6]


array([1, 3, 4, 6])

In [50]:
a = np.random.randint(1, 20, size=20)
b = np.random.randint(1, 10, size=10)
print(a, b, sep='\n\n')
np.union1d(a, b)

[ 7 14 19 10  5 18  6  8 12  3 16 15 14  2  3  2 14 14  8  6]

[6 6 2 9 6 2 2 2 6 8]


array([ 2,  3,  5,  6,  7,  8,  9, 10, 12, 14, 15, 16, 18, 19])

In [53]:
a = np.random.randint(1, 20, size=20)
b = np.random.randint(1, 10, size=10)
print(a, b, sep='\n\n')
np.setdiff1d(a, b)

[11  8 11 14 12  6 16 16 14 13  6 16 13  5 12  9 17 19 10  7]

[2 1 4 4 5 8 2 6 2 7]


array([ 9, 10, 11, 12, 13, 14, 16, 17, 19])

In [54]:
np.setxor1d(a, b)
# xor 
# 0, 0 - 0
# 1, 0 - 1
# 0, 1 - 1
# 1, 1 - 0
# all these  from book chapter 4, 4.4
# explore uit and saylani-a.i repository on enggqasim

array([ 1,  2,  4,  9, 10, 11, 12, 13, 14, 16, 17, 19])